model:
  channels: 16
  num_blocks: 7
  semantic_classes: 15
  instance_classes: 14
  sem2ins_classes: []
  semantic_only: False
  semantic_weight: [1.0, 1.0, 44.0, 21.9, 1.8, 25.1, 31.5, 21.8, 24.0, 54.4, 114.4, 81.2, 43.6, 9.7, 22.4]
  with_coords: False
  ignore_label: -100
  voxel_scale: 3
  use_spp_pool: False
  filter_bg_thresh: 0.1
  iterative_sampling: False
  mask_dim_out: 32
  instance_head_cfg:
    num_dyco_layer: 2
    dec_dim: 64
    n_sample_pa1: 2048
    n_queries: 256
    radius_scale: 10
    radius: 0.4
    neighbor: 16
  test_cfg:
    x4_split: False
    logit_thresh: 0.0
    score_thresh: 0.2
    npoint_thresh: 10
    type_nms: 'matrix'
    topk: 100

  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear', 'offset_vertices_linear', 'box_conf_linear']

data:
  train:
    type: 'stpls3d'
    data_root: 'dataset/stpls3d'
    prefix: 'train'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 3
    voxel_cfg:
      scale: 3
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'stpls3d'
    data_root: 'dataset/stpls3d'
    prefix: 'val'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 3
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000


dataloader:
  train:
    batch_size: 32
    num_workers: 16
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'AdamW'
  lr: 0.001
  weight_decay: 0.0001

save_cfg:
  semantic: False
  offset: False
  instance: True
  offset_vertices: False
  nmc_clusters: False
  object_conditions: False

fp16: True
epochs: 120
step_epoch: 50
save_freq: 4
pretrain: 'pretrains/stpls3d/pretrain_stpls3d_val.pth'
work_dir: ''
