foundation_model:
  grounded_config_file: './GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py'
  grounded_checkpoint: './pretrains/foundation_models/groundingdino_swint_ogc.pth'
  sam_checkpoint: './pretrains/foundation_models/sam_vit_h_4b8939.pth'
  clip_model: 'ViT-L-14-336'
  clip_checkpoint: 'openai'
  device: 'cuda'
  box_threshold: 0.4
  text_threshold: 0.4
  clip_dim: 768


grounded_feature:
  granularity: 0.8

data:
  dataset_name: 'scannet200'
  split_path: './open3dis/dataset/scannetv2_val.txt'
  datapath: './data/ScannetV2/ScannetV2_2D_5interval/val'
  gt_pth: './data/Scannet200/val'
  spp_path: './data/Scannet200/superpoints'
  cls_agnostic_3d_proposals_path: './data/Scannet200/isbnet_clsagnostic_scannet200'
  dc_features_path: './data/Scannet200/dc_feat_scannet200'
  img_dim: [640, 480]
  rgb_img_dim: [1296, 968]
  cut_num_pixel_boundary: 10
  img_interval: 2

cluster:
  visi: 0.9
  simi: 0.9
  point_visi: 0.2
  valid_points: 50

refine_grounding:
  top_k: 5

final_instance:
  iou_overlap: 0.9
  top_k: 300
  scale_semantic_score: 300.0

exp:
  exp_name: "version_final"
  mask2d_output: 'maskGdino'
  grounded_feat_output: 'grounded_feat'
  refined_grounded_feat_output: 'refined_grounded_feat'
  clustering_3d_output: 'hier_agglo'
  final_output: 'final_result_hier_agglo'
  save_dir: './exp'


fp16: True