model:
  channels: 32
  num_blocks: 7
  semantic_classes: 100
  instance_classes: 84
  sem2ins_classes: []
  semantic_only: True
  semantic_weight: False
  with_coords: True
  ignore_label: -100
  voxel_scale: 50
  use_spp_pool: True
  filter_bg_thresh: 0.1
  iterative_sampling: True
  instance_head_cfg:
    num_dyco_layer: 2 # dyco 2
    dec_dim: 128
    n_sample_pa1: 2048
    n_queries: 256
    radius_scale: 1
    radius: 0.4
    neighbor: 32
  test_cfg:
    x4_split: False
    logit_thresh: 0.0
    score_thresh: 0.2
    npoint_thresh: 100
    type_nms: 'matrix'
    topk: 100

  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear', 'offset_vertices_linear', 'box_conf_linear']

data:
  train:
    type: 'scannetpp_benchmark84'
    data_root: '../../../Dataset/Scannetpp/Scannetpp_3D/train'
    prefix: 'groundtruth_benchmark_instance'
    suffix: '.pth'
    training: True
    repeat: 4
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'scannetpp_benchmark84'
    data_root: '../../../Dataset/Scannetpp/Scannetpp_3D/val'
    prefix: 'groundtruth_benchmark_instance'
    suffix: '.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000


dataloader:
  train:
    batch_size: 8
    num_workers: 8
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'AdamW'
  lr: 0.001
  weight_decay: 0.0001

save_cfg:
  semantic: False
  offset: False
  instance: True
  offset_vertices: False
  nmc_clusters: False
  object_conditions: False

fp16: False
epochs: 120
step_epoch: 50
save_freq: 4
pretrain: ''
work_dir: '../../../scannetpp_84'

# best weight: pretrains/best_baseline.pth
